# Generated by Django 4.2.4 on 2023-08-18 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('world_news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='Business/images')),
                ('inline_category', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('description', models.TextField(verbose_name='Yangilik matni')),
            ],
        ),
        migrations.CreateModel(
            name='EntertainmentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='Entertainment/images')),
                ('inline_category', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('description', models.TextField(verbose_name='Yangilik matni')),
            ],
        ),
        migrations.CreateModel(
            name='LifeStylePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='LifeStyle/images')),
                ('inline_category', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('description', models.TextField(verbose_name='Yangilik matni')),
            ],
        ),
        migrations.CreateModel(
            name='TravelPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='Business/images')),
                ('inline_category', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('description', models.TextField(verbose_name='Yangilik matni')),
            ],
        ),
        migrations.AddField(
            model_name='newstitle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='newstitle',
            name='post_category',
            field=models.CharField(default='Game', max_length=255, verbose_name='Ichki kategoriya'),
        ),
        migrations.AddField(
            model_name='newstitle',
            name='powered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newstitle',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='categorynewstitle',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Title in the category site'),
        ),
        migrations.AlterField(
            model_name='newstitle',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world_news.categorynewstitle', verbose_name='Yangilik turi'),
        ),
        migrations.AlterField(
            model_name='newstitle',
            name='description',
            field=models.TextField(verbose_name='Yangilik matni'),
        ),
        migrations.AlterField(
            model_name='newstitle',
            name='photo',
            field=models.ImageField(upload_to='title/images'),
        ),
        migrations.AlterField(
            model_name='newstitle',
            name='title',
            field=models.CharField(max_length=350, verbose_name='Sarlavha'),
        ),
        migrations.CreateModel(
            name='CommentNewsTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('news_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world_news.newstitle')),
            ],
        ),
    ]
